apiVersion: v1
kind: Service
metadata:
  name: train-model-metrics
  namespace: kubeflow
  labels:
    app: train-model
spec:
  selector:
    app: train-model  # ⚠️ Must match the label of your training pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
