apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-exporter
  template:
    metadata:
      labels:
        app: metrics-exporter
    spec:
      containers:
        - name: exporter
          image: sirvaiys/metric_image:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter-service
  namespace: kubeflow
spec:
  selector:
    app: metrics-exporter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
